Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vbguest.iso_path = "/usr/share/virtualbox/VBoxGuestAdditions.iso"
end
