
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.define :ssh_forward do |t|
  end
  # line to forward active ssh agent from host to guest
  config.ssh.forward_agent = true
  config.vm.provision :shell, path: "bootstrap.sh"
end
