
Vagrant.configure("2") do |config|
  config.vm.box = "pogosoftware/ubuntu-18.04-docker"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.provision "shell", inline: <<-SHELL
     git clone https://github.com/datawire/hello-world.git

  SHELL
end
